# download file
####
GET http://yt-downloader.deploy.cbs.co.id/?id=ID126AB&url=https://www.youtube.com/c/Rfmofficialpagetr/videos&limit=1 HTTP/1.1
content-type: application/json


#search by userid / title / description / youtube keywords
####
GET http://localhost:3000/search?keyword=audio&limit=3&skip=6 HTTP/1.1
content-type: application/json




# local testing
####
GET http://localhost:3000/?id=ID126AB&url=https://www.youtube.com/c/Rfmofficialpagetr/videos&limit=1 HTTP/1.1
content-type: application/json


####
GET http://localhost:3000/search?keyword=ID126AB&limit=3&skip=6 HTTP/1.1
content-type: application/json